/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SchMgt__factory } from "./SchMgt__factory";
export { SchoolMgt__factory } from "./SchoolMgt__factory";
