/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { SchoolMgt } from "./SchoolMgt";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { SchoolMgt__factory } from "./factories/SchoolMgt__factory";
