/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SchoolMgt {
  export type StudentStruct = {
    name: string;
    age: BigNumberish;
    grade: BigNumberish;
    gender: BigNumberish;
    status: BigNumberish;
  };

  export type StudentStructOutput = [
    name: string,
    age: bigint,
    grade: bigint,
    gender: bigint,
    status: bigint
  ] & {
    name: string;
    age: bigint;
    grade: bigint;
    gender: bigint;
    status: bigint;
  };
}

export interface SchoolMgtInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllStudents"
      | "getStudent"
      | "principal"
      | "registerStudent"
      | "studentCount"
      | "students"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StudentRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "principal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerStudent",
    values: [AddressLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStudent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "principal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
}

export namespace StudentRegisteredEvent {
  export type InputTuple = [id: BigNumberish, name: string];
  export type OutputTuple = [id: bigint, name: string];
  export interface OutputObject {
    id: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SchoolMgt extends BaseContract {
  connect(runner?: ContractRunner | null): SchoolMgt;
  waitForDeployment(): Promise<this>;

  interface: SchoolMgtInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllStudents: TypedContractMethod<
    [],
    [SchoolMgt.StudentStructOutput[]],
    "view"
  >;

  getStudent: TypedContractMethod<
    [_id: BigNumberish],
    [SchoolMgt.StudentStructOutput],
    "view"
  >;

  principal: TypedContractMethod<[], [string], "view">;

  registerStudent: TypedContractMethod<
    [
      _studentAddress: AddressLike,
      _name: string,
      _age: BigNumberish,
      _gender: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  studentCount: TypedContractMethod<[], [bigint], "view">;

  students: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        name: string;
        age: bigint;
        grade: bigint;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllStudents"
  ): TypedContractMethod<[], [SchoolMgt.StudentStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getStudent"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [SchoolMgt.StudentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "principal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerStudent"
  ): TypedContractMethod<
    [
      _studentAddress: AddressLike,
      _name: string,
      _age: BigNumberish,
      _gender: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "studentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        name: string;
        age: bigint;
        grade: bigint;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "StudentRegistered"
  ): TypedContractEvent<
    StudentRegisteredEvent.InputTuple,
    StudentRegisteredEvent.OutputTuple,
    StudentRegisteredEvent.OutputObject
  >;

  filters: {
    "StudentRegistered(uint256,string)": TypedContractEvent<
      StudentRegisteredEvent.InputTuple,
      StudentRegisteredEvent.OutputTuple,
      StudentRegisteredEvent.OutputObject
    >;
    StudentRegistered: TypedContractEvent<
      StudentRegisteredEvent.InputTuple,
      StudentRegisteredEvent.OutputTuple,
      StudentRegisteredEvent.OutputObject
    >;
  };
}
